/**
 * The old video history store, and the one-time move out of it.
 *
 * Before the studio, clips lived in a flat "recent generations" list in the
 * browser. Nothing writes to it any more — the studio's project library
 * replaced it — but people still have clips in there, and quietly stranding
 * someone's work behind a UI change is not acceptable. So the list is still
 * readable, and the video studio imports it into the project library the first
 * time it loads.
 *
 * The raw list is left in place rather than deleted. If the import goes wrong
 * the original is still there to look at, and a second import can't happen
 * because of the flag below.
 */

import { projectTitle, type StudioProject, type StudioClip } from "./studio-projects";

export interface VideoHistoryItem {
  id: string;
  url: string;
  /** signature from our poll endpoint, needed to read frames back via the proxy */
  token?: string;
  /** clips generated by extending an earlier one share a chain id */
  chainId?: string;
  /** position within the chain, 1-based */
  part?: number;
  prompt: string;
  modelName: string;
  duration: number;
  resolution: string;
  /** optional: clips saved before this was recorded simply keep the current ratio */
  aspectRatio?: string;
  /** which chat project this clip belonged to, when it belonged to one */
  projectId?: string | null;
  audio: boolean;
  seed?: number;
  createdAt: number;
}

const STORAGE_KEY = "cfai_video_history";
const MIGRATED_KEY = "cfai_studio_video_migrated";
const MAX_ITEMS = 30;

export function loadHistory(): VideoHistoryItem[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? (JSON.parse(raw) as VideoHistoryItem[]) : [];
  } catch {
    return [];
  }
}

export function saveHistory(items: VideoHistoryItem[]) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items.slice(0, MAX_ITEMS)));
  } catch {
    /* storage full — history is a convenience, not load-bearing */
  }
}

/**
 * Turn the old flat list into studio projects, once.
 *
 * A chain (a clip and everything extended from it) becomes one project, in
 * playback order — that is what a chain always meant, and it is exactly what a
 * studio project is. Unchained clips each become their own single-clip
 * project rather than being lumped together, because guessing that two
 * unrelated renders belong side by side would be worse than leaving them
 * apart.
 *
 * Returns [] on every subsequent call, so it is safe to call on every mount.
 */
export function migrateVideoHistory(): StudioProject[] {
  if (typeof window === "undefined") return [];
  try {
    if (localStorage.getItem(MIGRATED_KEY)) return [];
  } catch {
    return [];
  }

  const items = loadHistory();
  try {
    localStorage.setItem(MIGRATED_KEY, "1");
  } catch {
    /* can't record the flag — better to skip than risk importing twice */
    return [];
  }
  if (!items.length) return [];

  const groups = new Map<string, VideoHistoryItem[]>();
  for (const item of items) {
    const key = item.chainId ?? item.id;
    const list = groups.get(key);
    if (list) list.push(item);
    else groups.set(key, [item]);
  }

  const projects: StudioProject[] = [];
  for (const [key, list] of groups) {
    list.sort((a, b) => (a.part ?? 0) - (b.part ?? 0) || a.createdAt - b.createdAt);
    const clips: StudioClip[] = list.map((item) => ({
      job_id: item.id,
      url: item.url,
      download: item.url,
      raw: item.url,
      model: item.modelName,
      dur: item.duration,
      res: item.resolution,
      aspect: item.aspectRatio ?? "16:9",
      prompt: item.prompt,
      ts: item.createdAt,
    }));
    projects.push({
      id: `p${key}`,
      title: projectTitle(list[0].prompt),
      ts: list[0].createdAt,
      clips,
    });
  }

  // newest first, matching how the studio orders everything else
  projects.sort((a, b) => b.ts - a.ts);
  return projects;
}
