import type { Metadata } from "next";

export const metadata: Metadata = { title: "Disclaimer — Chat Free AI" };

export default function DisclaimerPage() {
  return (
    <section className="px-6 py-14">
      <article className="mx-auto max-w-2xl">
        <h1 className="font-display text-3xl font-semibold tracking-tight">Disclaimer</h1>
        <div className="mt-8 space-y-6 text-[15px] leading-relaxed text-ink-mute">
          <p>
            Content on this site is generated by third-party AI models. AI output can be inaccurate,
            outdated, biased or inappropriate, and nothing produced here constitutes professional
            advice — medical, legal, financial or otherwise. Verify important information
            independently before acting on it.
          </p>
          <p>
            Model names (ChatGPT, Claude, Gemini, Deepseek, Llama, Qwen, Grok, Sora, Veo and others)
            are trademarks of their respective owners. Chat Free AI is an independent service and is
            not affiliated with, endorsed by or sponsored by those companies.
          </p>
          <p>
            Approximate counts on the pricing page (videos, images, tokens per package) are
            estimates that depend on the models, lengths, resolutions and sizes you choose.
          </p>
        </div>
      </article>
    </section>
  );
}
